version: 3

tasks:
  build:
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - go build -o release/{{.GOOS}}/{{.GOARCH}}/echelon

  start:
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - ./release/{{.GOOS}}/{{.GOARCH}}/echelon worker -e {{.ENV_FILE | default "local.env"}}

  build-image:
    cmds:
      - docker build -t ppal31/echelon:{{.TAG | default "latest"}} .
